base_url = "https://pixeleden.com/"

# The site title and description; used in feeds by default.
title = "Pixeleden | A Digital Garden and Journal of Allan Reyes"
description = "Tech and design blog of Allan Reyes. A digital product designer based on Madrid, Spain."

# The default language, used in RSS
default_language = "en"

compile_sass = true
generate_feeds = true
build_search_index = true
generate_robots_txt = true

taxonomies = [
    { name = "tags", feed = true },           # each tag will have its own feed
    { name = "categories", paginate_by = 5 }, # 5 items per page for a term
    { name = "authors" },                     # Basic definition: no feed or pagination
]

[markdown]
# When set to "true", all code blocks are highlighted.
highlight_code = true

[slugify]
paths = "on"
anchors = "on"


[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
include_path = false
# Whether to include the rendered content of the page/section in the index
include_content = true

[extra]
# Put all your custom variables here
author = "Allan Reyes"
github = "https://github.com/ulampinoy"
