base_url = "/"
compile_sass = true
generate_rss = false
hard_link_static = true
highlight_code = true
highlight_theme = "monokai"
build_search_index = true

# Used in RSS by default
title = "Pixeleden | A Digital Garden and Journal of Allan Reyes"
description = "Tech and design blog of Allan Reyes. A digital product designer based on Madrid, Spain"
# The default language, used in RSS
default_language = "en"
