base_url = "https://pixeleden.com/"
compile_sass = true
generate_rss = true
highlight_code = true
highlight_theme = "charcoal"
build_search_index = true

# Used in RSS by default
title = "Pixeleden | A Digital Garden and Journal of Allan Reyes"
description = "Tech and design blog of Allan Reyes. A digital product designer based on Madrid, Spain"

# The default language, used in RSS
default_language = "en"

generate_categories_pages = true
generate_tags_pages = true

[extra]
# Put all your custom variables here
author = "Allan Reyes"
github = "https://github.com/ulampinoy"